In [203]:
import pysftp
import sys
import os
import pandas as pd

In [204]:
#download files again (yes/no)?
download = "yes"

#set year for data creation
year = '2024'

In [205]:
#ENTSO-E sftp settings
host = "sftp-transparency.entsoe.eu"
password = "3?mJ}V4us?!L}5E"                
username = "jsavelsberg@ethz.ch"                
port = '22'

In [206]:
#cnopts = pysftp.CnOpts()  # Leon, da ich pysftp 0.2.8 nutze
#cnopts.hostkeys = None

In [207]:
dir_out = "../parsed_data/"

In [208]:
#Connect to ENTSO-E Transparency FTP
#for this to work, pysftp 0.2.8 is needed!
path = '/TP_export/'
path_local = os.path.join(os.pardir,'source_data/ENTSOE/')

In [209]:
with pysftp.Connection(host=host, username=username, password=password) as sftp:
    print("Connection succesfully established.")

    # show list of files
    files = sftp.listdir('/TP_export/')   
    print(files)

Connection succesfully established.
['AcceptedAggregatedOffers_17.1.D', 'ActivatedBalancingEnergy_17.1.E', 'ActualCapacitiesAndOutlookOnFrequencyRestorationReserveAndReplacementReserve_SOGL_188.3_188.4_189.2_189.3_r3', 'ActualGenerationOutputPerGenerationUnit_16.1.A_r2.1', 'ActualTotalLoad_6.1.A', 'AggregatedBalancingEnergyBids_12.3.E_r3', 'AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D', 'AggregatedGenerationPerType_16.1.B_C', 'AmountAndPricesPaidOfBalancingReservesUnderContract_17.1.B_C_r2', 'AmountOfBalancingReservesUnderContract_17.1.B', 'BalancingBorderCapacityLimitations_IFs_4.3_4.4_r2', 'ChangesInActualAvailabilityOfConsumptionUnits_7.1.B', 'ChangesInActualAvailabilityOfOffshoreGridInfrastructureReasons_10.1.C', 'ChangesInActualAvailabilityOfOffshoreGridInfrastructure_10.1.C', 'ChangesToBidAvailability_IFs_mFRR9.9_aFRR9.6_9.8_r3', 'CommercialSchedulesNetPositions_12.1.F_r3', 'CommercialSchedules_12.1.F_r3', 'CostsOfCongestionManagement_13.1.C', 'Countertrading_13.1.B_r2.1', 'CrossBorderBalancingEnergyActivated_17.1.J', 'CrossBorderBalancingPrices_17.1.J', 'CrossBorderBalancingVolumesOfExchangedBidsAndOffers_17.1.J', 'CrossBorderCapacityForDcLinksIntraday_11.3', 'CrossBorderMarginalPriceForAutomaticFrequencyRestorationReserveStandardProduct_IF_aFRR3.16_r3', 'CrossZonalBalancingCapacity_12.3.H_12.3.I_r3', 'CurrentBalancingState_12.3.A_r3', 'CurrentGenerationForecastForWindAndSolar_14.1.D', 'DayAheadAggregatedGeneration_14.1.C', 'DayAheadFlowBasedAllocations_11.1', 'DayAheadGenerationForecastForWindAndSolar_14.1.D', 'DayAheadTotalLoadForecast_6.1.B', 'ElasticDemands_IFs_mFRR3.4_aFRR3.4_r3', 'EnergyPrices_12.1.D_r3', 'ExchangedReserveCapacity_SOGL_190.3_r3', 'ExpansionAndDismantlingProjects_9.1', 'ExplicitAllocationsAuctionRevenueDaily_12.3.A', 'ExplicitAllocationsAuctionRevenueIntraday_12.3.A', 'ExplicitAllocationsAuctionRevenueMonthly_12.3.A', 'ExplicitAllocationsAuctionRevenueOther_12.3.A', 'ExplicitAllocationsAuctionRevenueWeekly_12.3.A', 'ExplicitAllocationsAuctionRevenueYearly_12.3.A', 'ExplicitAllocationsUseOfTransferCapacityDaily_12.1.A', 'ExplicitAllocationsUseOfTransferCapacityIntraday_12.1.A', 'ExplicitAllocationsUseOfTransferCapacityMonthly_12.1.A', 'ExplicitAllocationsUseOfTransferCapacityOther_12.1.A', 'ExplicitAllocationsUseOfTransferCapacityWeekly_12.1.A', 'ExplicitAllocationsUseOfTransferCapacityYearly_12.1.A', 'Export_log.csv', 'Export_log_r3.csv', 'Export_oce_log_r3.csv', 'Fallbacks_IF_IN7.2_mFRR3.11_aFRR3.10_r3', 'FcrTotalCapacity_187.2', 'FinancialExpensesAndIncomeForBalancing_17.1.I', 'FinancialExpensesAndIncomeForBalancing_17.1.I_r3', 'FlowBasedAllocationsCongestionIncomeDaily_12.1.E', 'FlowBasedAllocationsCongestionIncome_12.1.E_r3', 'ForecastedDayAheadTransferCapacities_11.1', 'ForecastedMonthAheadTransferCapacities_11.1', 'ForecastedWeekAheadTransferCapacities_11.1', 'ForecastedYearAheadTransferCapacities_11.1', 'FrequencyContainmentReserveAmountAndShares_SOGL_187.2_r3', 'FrrActualCapacity_188.4', 'ImbalancePrices_17.1.G_r2.1', 'ImplicitAllocationsCongestionIncome_12.1.E_r3', 'ImplicitAllocationsNetPositions_12.1.E_r3', 'InstalledCapacityProductionUnit_14.1.B', 'InstalledGenerationCapacityAggregated_14.1.A', 'IntradayGenerationForecastForWindAndSolar_14.1.D', 'MonthAheadTotalLoadForecast_6.1.D', 'NettedAndExchangedVolumesPerBorder_IFs_IN3.10_mFRR3.17_r3', 'NettedAndExchangedVolumes_IFs_IN3.10_mFRR3.17_r3', 'OfferedDayAheadTransferCapacityImplicit_11.1', 'OfferedDayAheadTransferCapacity_11.1', 'OfferedIntradayTransferCapacityImplicit_11.1', 'OfferedIntradayTransferCapacity_11.1', 'OfferedMonthAheadTransferCapacity_11.1', 'OfferedOtherTransferCapacity_11.1', 'OfferedTransferCapacitiesContinuous_11.1_r3', 'OfferedTransferCapacitiesExplicit_11.1_r3', 'OfferedTransferCapacitiesImplicit_11.1_r3', 'OfferedWeekAheadTransferCapacity_11.1', 'OfferedYearAheadTransferCapacity_11.1', 'OtherMarketInformation_r3', 'PermanentAllocationLimitations_IFs_4.5_r3', 'PhysicalFlows_12.1.G', 'PlannedUnavailabilityOfConsumptionUnits_7.1.A', 'PricesOfActivatedBalancingEnergy_17.1.F_r3', 'PricesOfProcuredBalancingReserves_17.1.C', 'ProcuredBalancingCapacity_12.3.F', 'ProcuredBalancingCapacity_12.3.F_r3', 'ProductionAndGenerationUnits_r2', 'RedispatchingCrossBorder_13.1.A_r2.1', 'RedispatchingInternal_13.1.A_r2.1', 'Redispatching_13.1.A', 'ResultsOfTheCriteriaApplicationProcess_SOGL_185.4_r3', 'RrActualCapacity_189.3', 'SharesOfFcrCapacity_187.2', 'TotalCapacityAlreadyAllocated_12.1.C_r3', 'TotalCapacityNominated_12.1.B', 'TotalImbalanceVolumes_17.1.H', 'TransferCapacitiesAllocatedWithThirdCountriesDailyImplicit_12.1.H', 'TransferCapacitiesAllocatedWithThirdCountriesDaily_12.1.H', 'TransferCapacitiesAllocatedWithThirdCountriesIntraday_12.1.H', 'TransferCapacitiesAllocatedWithThirdCountriesMonthly_12.1.H', 'TransferCapacitiesAllocatedWithThirdCountriesYearly_12.1.H', 'TransferCapacitiesAllocatedWithThirdCountries_12.1.H_r3', 'UnavailabilityInTransmissionGridReasons_10.1.A_B', 'UnavailabilityInTransmissionGrid_10.1.A_B', 'UnavailabilityOfGenerationUnitsReasons_15.1.A_B', 'UnavailabilityOfGenerationUnits_15.1.A_B', 'UnavailabilityOfProductionUnitsReasons_15.1.C_D', 'UnavailabilityOfProductionUnits_15.1.C_D', 'UseOfAllocatedCrossZonalBalancingCapacity_12.3.H_12.3.I_r2', 'WeekAheadTotalLoadForecast_6.1.C', 'YearAheadForecastMargin_8.1', 'YearAheadTotalLoadForecast_6.1.E', 'zip']

In [210]:
# Leon: 
with pysftp.Connection(host=host, username=username, password=password) as sftp:
    print("Inhalt von /TP_export/ActualTotalLoad_6.1.A/:")
    print(sftp.listdir('/TP_export/ActualTotalLoad_6.1.A/'))

Inhalt von /TP_export/ActualTotalLoad_6.1.A/:
['2014_12_ActualTotalLoad_6.1.A.csv', '2015_01_ActualTotalLoad_6.1.A.csv', '2015_02_ActualTotalLoad_6.1.A.csv', '2015_03_ActualTotalLoad_6.1.A.csv', '2015_04_ActualTotalLoad_6.1.A.csv', '2015_05_ActualTotalLoad_6.1.A.csv', '2015_06_ActualTotalLoad_6.1.A.csv', '2015_07_ActualTotalLoad_6.1.A.csv', '2015_08_ActualTotalLoad_6.1.A.csv', '2015_09_ActualTotalLoad_6.1.A.csv', '2015_10_ActualTotalLoad_6.1.A.csv', '2015_11_ActualTotalLoad_6.1.A.csv', '2015_12_ActualTotalLoad_6.1.A.csv', '2016_01_ActualTotalLoad_6.1.A.csv', '2016_02_ActualTotalLoad_6.1.A.csv', '2016_03_ActualTotalLoad_6.1.A.csv', '2016_04_ActualTotalLoad_6.1.A.csv', '2016_05_ActualTotalLoad_6.1.A.csv', '2016_06_ActualTotalLoad_6.1.A.csv', '2016_07_ActualTotalLoad_6.1.A.csv', '2016_08_ActualTotalLoad_6.1.A.csv', '2016_09_ActualTotalLoad_6.1.A.csv', '2016_10_ActualTotalLoad_6.1.A.csv', '2016_11_ActualTotalLoad_6.1.A.csv', '2016_12_ActualTotalLoad_6.1.A.csv', '2017_01_ActualTotalLoad_6.1.A.csv', '2017_02_ActualTotalLoad_6.1.A.csv', '2017_03_ActualTotalLoad_6.1.A.csv', '2017_04_ActualTotalLoad_6.1.A.csv', '2017_05_ActualTotalLoad_6.1.A.csv', '2017_06_ActualTotalLoad_6.1.A.csv', '2017_07_ActualTotalLoad_6.1.A.csv', '2017_08_ActualTotalLoad_6.1.A.csv', '2017_09_ActualTotalLoad_6.1.A.csv', '2017_10_ActualTotalLoad_6.1.A.csv', '2017_11_ActualTotalLoad_6.1.A.csv', '2017_12_ActualTotalLoad_6.1.A.csv', '2018_01_ActualTotalLoad_6.1.A.csv', '2018_02_ActualTotalLoad_6.1.A.csv', '2018_03_ActualTotalLoad_6.1.A.csv', '2018_04_ActualTotalLoad_6.1.A.csv', '2018_05_ActualTotalLoad_6.1.A.csv', '2018_06_ActualTotalLoad_6.1.A.csv', '2018_07_ActualTotalLoad_6.1.A.csv', '2018_08_ActualTotalLoad_6.1.A.csv', '2018_09_ActualTotalLoad_6.1.A.csv', '2018_10_ActualTotalLoad_6.1.A.csv', '2018_11_ActualTotalLoad_6.1.A.csv', '2018_12_ActualTotalLoad_6.1.A.csv', '2019_01_ActualTotalLoad_6.1.A.csv', '2019_02_ActualTotalLoad_6.1.A.csv', '2019_03_ActualTotalLoad_6.1.A.csv', '2019_04_ActualTotalLoad_6.1.A.csv', '2019_05_ActualTotalLoad_6.1.A.csv', '2019_06_ActualTotalLoad_6.1.A.csv', '2019_07_ActualTotalLoad_6.1.A.csv', '2019_08_ActualTotalLoad_6.1.A.csv', '2019_09_ActualTotalLoad_6.1.A.csv', '2019_10_ActualTotalLoad_6.1.A.csv', '2019_11_ActualTotalLoad_6.1.A.csv', '2019_12_ActualTotalLoad_6.1.A.csv', '2020_01_ActualTotalLoad_6.1.A.csv', '2020_02_ActualTotalLoad_6.1.A.csv', '2020_03_ActualTotalLoad_6.1.A.csv', '2020_04_ActualTotalLoad_6.1.A.csv', '2020_05_ActualTotalLoad_6.1.A.csv', '2020_06_ActualTotalLoad_6.1.A.csv', '2020_07_ActualTotalLoad_6.1.A.csv', '2020_08_ActualTotalLoad_6.1.A.csv', '2020_09_ActualTotalLoad_6.1.A.csv', '2020_10_ActualTotalLoad_6.1.A.csv', '2020_11_ActualTotalLoad_6.1.A.csv', '2020_12_ActualTotalLoad_6.1.A.csv', '2021_01_ActualTotalLoad_6.1.A.csv', '2021_02_ActualTotalLoad_6.1.A.csv', '2021_03_ActualTotalLoad_6.1.A.csv', '2021_04_ActualTotalLoad_6.1.A.csv', '2021_05_ActualTotalLoad_6.1.A.csv', '2021_06_ActualTotalLoad_6.1.A.csv', '2021_07_ActualTotalLoad_6.1.A.csv', '2021_08_ActualTotalLoad_6.1.A.csv', '2021_09_ActualTotalLoad_6.1.A.csv', '2021_10_ActualTotalLoad_6.1.A.csv', '2021_11_ActualTotalLoad_6.1.A.csv', '2021_12_ActualTotalLoad_6.1.A.csv', '2022_01_ActualTotalLoad_6.1.A.csv', '2022_02_ActualTotalLoad_6.1.A.csv', '2022_03_ActualTotalLoad_6.1.A.csv', '2022_04_ActualTotalLoad_6.1.A.csv', '2022_05_ActualTotalLoad_6.1.A.csv', '2022_06_ActualTotalLoad_6.1.A.csv', '2022_07_ActualTotalLoad_6.1.A.csv', '2022_08_ActualTotalLoad_6.1.A.csv', '2022_09_ActualTotalLoad_6.1.A.csv', '2022_10_ActualTotalLoad_6.1.A.csv', '2022_11_ActualTotalLoad_6.1.A.csv', '2022_12_ActualTotalLoad_6.1.A.csv', '2023_01_ActualTotalLoad_6.1.A.csv', '2023_02_ActualTotalLoad_6.1.A.csv', '2023_03_ActualTotalLoad_6.1.A.csv', '2023_04_ActualTotalLoad_6.1.A.csv', '2023_05_ActualTotalLoad_6.1.A.csv', '2023_06_ActualTotalLoad_6.1.A.csv', '2023_07_ActualTotalLoad_6.1.A.csv', '2023_08_ActualTotalLoad_6.1.A.csv', '2023_09_ActualTotalLoad_6.1.A.csv', '2023_10_ActualTotalLoad_6.1.A.csv', '2023_11_ActualTotalLoad_6.1.A.csv', '2023_12_ActualTotalLoad_6.1.A.csv', '2024_01_ActualTotalLoad_6.1.A.csv', '2024_02_ActualTotalLoad_6.1.A.csv', '2024_03_ActualTotalLoad_6.1.A.csv', '2024_04_ActualTotalLoad_6.1.A.csv', '2024_05_ActualTotalLoad_6.1.A.csv', '2024_06_ActualTotalLoad_6.1.A.csv', '2024_07_ActualTotalLoad_6.1.A.csv', '2024_08_ActualTotalLoad_6.1.A.csv', '2024_09_ActualTotalLoad_6.1.A.csv', '2024_10_ActualTotalLoad_6.1.A.csv', '2024_11_ActualTotalLoad_6.1.A.csv', '2024_12_ActualTotalLoad_6.1.A.csv', '2025_01_ActualTotalLoad_6.1.A.csv', '2025_02_ActualTotalLoad_6.1.A.csv', '2025_03_ActualTotalLoad_6.1.A.csv', '2025_04_ActualTotalLoad_6.1.A.csv', '2025_05_ActualTotalLoad_6.1.A.csv', '2025_06_ActualTotalLoad_6.1.A.csv', '2025_07_ActualTotalLoad_6.1.A.csv']

## load data

In [211]:
#set paths and get file names
path_load = path+'ActualTotalLoad_6.1.A/'
path_load_local = path_local+'load/'

# Leon: (Ordner sicherstellen)
os.makedirs(path_load_local, exist_ok=True)

with pysftp.Connection(host=host, username=username, password=password) as sftp:
    print("Connection succesfully established.")
    # show list of files
    files = sftp.listdir(path_load)
    #download files
    if year != "":
        files = [i for i in files if year in i]
    print(files)

Connection succesfully established.
['2024_01_ActualTotalLoad_6.1.A.csv', '2024_02_ActualTotalLoad_6.1.A.csv', '2024_03_ActualTotalLoad_6.1.A.csv', '2024_04_ActualTotalLoad_6.1.A.csv', '2024_05_ActualTotalLoad_6.1.A.csv', '2024_06_ActualTotalLoad_6.1.A.csv', '2024_07_ActualTotalLoad_6.1.A.csv', '2024_08_ActualTotalLoad_6.1.A.csv', '2024_09_ActualTotalLoad_6.1.A.csv', '2024_10_ActualTotalLoad_6.1.A.csv', '2024_11_ActualTotalLoad_6.1.A.csv', '2024_12_ActualTotalLoad_6.1.A.csv']

In [212]:
#download aggregated load data (ActualTotalLoad)
if download =="yes":
    with pysftp.Connection(host=host, username=username, password=password) as sftp:
        for file in files:
            sftp.get(path_load+file,path_load_local+file)
            print('Successfully downloaded file '+file)

Successfully downloaded file 2024_01_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_02_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_03_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_04_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_05_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_06_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_07_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_08_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_09_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_10_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_11_ActualTotalLoad_6.1.A.csv
Successfully downloaded file 2024_12_ActualTotalLoad_6.1.A.csv

In [213]:
#Leon
import chardet
# Eine der Datein testen
test_file = path_load_local + files[0]
print("Prüfe Datei:", test_file)

# Encoding automatisch erkennen
with open(test_file, 'rb') as f:
    result = chardet.detect(f.read(50000)) # nur ersten Teil lesen
print("Erkanntes Encoding:", result)

# Datei mit erkanntem Encoding laden
df_test = pd.read_csv(test_file, sep="\t", encoding=result['encoding'], nrows=5)
print("Spalten:", df_test.columns.tolist())

Prüfe Datei: ..\source_data/ENTSOE/load/2024_01_ActualTotalLoad_6.1.A.csv
Erkanntes Encoding: {'encoding': 'UTF-8-SIG', 'confidence': 1.0, 'language': ''}
Spalten: ['DateTime', 'ResolutionCode', 'AreaCode', 'AreaTypeCode', 'AreaName', 'MapCode', 'TotalLoadValue', 'UpdateTime']

In [214]:
#combine files to one data frame
df_load = pd.DataFrame()
for file in files:
    df_temp = pd.read_csv(path_load_local+file,
                          decimal=".",encoding="UTF-8-SIG",sep="\t",  # Leon: updated encoding
                          parse_dates=True, index_col="DateTime").drop("AreaCode", axis=1)
    #df_load = df_load.append(df_temp)
    df_load = pd.concat([df_load, df_temp], ignore_index=False) # Leon, in pandas 2.0 gibt es .append() nicht mehr als Methode
df_load = df_load[df_load.AreaTypeCode == "CTY"].drop(["AreaTypeCode",'ResolutionCode','AreaName','UpdateTime'], axis=1).reset_index()
df_load = df_load.sort_values(by=['DateTime'])
df_load.info()

<class 'pandas.core.frame.DataFrame'>
Index: 655278 entries, 2111 to 654075
Data columns (total 3 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DateTime        655278 non-null  datetime64[ns]
 1   MapCode         655278 non-null  object
 2   TotalLoadValue  655278 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 20.0+ MB

In [215]:
df_load = df_load.rename(columns={"MapCode": "country", 'DateTime':'date','TotalLoadValue':'load'})
df_load = df_load.pivot_table("load", "date", "country")

In [216]:
df_load.head()

country,AL,AT,BA,BE,BG,CH,CY,CZ,DE,DK,...,NL,NO,PL,PT,RO,RS,SE,SI,SK,XK
date,,,,,,,,,,,,,,,,,,,,,
2024-01-01 00:00:00,731.0,5577.6,836.68,7335.32,3743.14,7692.42,414.94,5087.95,39336.85,3704.45,...,11311.90,18363.75,13695.19,5135.2,5046.0,4021.0,16763.0,891.70,2280.0,1132.36
2024-01-01 00:15:00,731.0,5511.2,NaN,7265.05,NaN,NaN,NaN,NaN,38991.10,NaN,...,11280.72,NaN,NaN,NaN,4986.0,NaN,NaN,NaN,NaN,NaN
2024-01-01 00:30:00,731.0,5443.6,NaN,7247.54,NaN,NaN,NaN,NaN,38615.81,NaN,...,11247.95,NaN,NaN,NaN,4947.0,NaN,NaN,NaN,NaN,NaN
2024-01-01 00:45:00,731.0,5389.6,NaN,7202.48,NaN,NaN,NaN,NaN,38328.84,NaN,...,11127.99,NaN,NaN,NaN,4916.0,NaN,NaN,NaN,NaN,NaN
2024-01-01 01:00:00,620.0,5423.6,815.14,7142.98,3608.08,7867.07,386.47,5005.89,38408.00,3638.33,...,11127.20,18224.37,13190.86,4962.5,4878.0,3863.0,16597.0,849.46,2252.0,1088.56

In [217]:
#some values are reported quarter hourly so we have to resample to hourly values
df_load_hourly = df_load.resample('1h').mean() # Leon, kleines h - wegen Warnung -

In [218]:
# Leon: 
df_load_hourly['AL']

date
2024-01-01 00:00:00     731.0
2024-01-01 01:00:00     620.0
2024-01-01 02:00:00     554.0
2024-01-01 03:00:00     523.0
2024-01-01 04:00:00     528.0
                        ...
2024-12-31 19:00:00    1356.0
2024-12-31 20:00:00    1212.0
2024-12-31 21:00:00    1140.0
2024-12-31 22:00:00    1093.0
2024-12-31 23:00:00     987.0
Freq: h, Name: AL, Length: 8784, dtype: float64

In [219]:
# Leon:
df_load_hourly['ME']

date
2024-01-01 00:00:00    307.91
2024-01-01 01:00:00    302.58
2024-01-01 02:00:00    280.81
2024-01-01 03:00:00    254.41
2024-01-01 04:00:00    259.18
                        ...
2024-12-31 19:00:00    529.92
2024-12-31 20:00:00    460.92
2024-12-31 21:00:00    430.49
2024-12-31 22:00:00    416.11
2024-12-31 23:00:00    393.84
Freq: h, Name: ME, Length: 8784, dtype: float64

Albania is completely missing so we copy profile from ME

In [220]:
#df_load_hourly['AL'] = df_load_hourly['ME']*0.0001 # Leon, nicht mehr nötig - wir haben Daten für AL
#df_load_hourly['AL']

In [221]:
#Lets see how complete values are
df_load_hourly.count().T

country
AL    8784
AT    8784
BA    8659
BE    8784
BG    8784
CH    8784
CY    2234
CZ    8784
DE    8784
DK    8784
EE    8782
ES    8784
FI    8784
FR    8784
GB    8551
GE    8347
GR    8783
HR    8784
HU    8784
IE    8680
IT    8784
LT    8784
LU    8784
LV    8784
MD    8609
ME    8784
MK    8400
NL    8784
NO    8784
PL    8784
PT    8784
RO    8784
RS    8784
SE    8784
SI    8743
SK    8764
XK    8778
dtype: int64

In [222]:
#Let's see how totals behave:
df_load_hourly.groupby(lambda x: x.year).sum().T/1000000
#they are too low so we prepare Eurostat yearly for upscaling in separate sheet

date           2024
country
AL         7.624728
AT        58.802005
BA         9.591011
BE        80.972093
BG        36.767205
CH        59.628942
CY         1.189922
CZ        60.923177
DE       465.508457
DK        36.780991
EE         7.950609
ES       232.286542
FI        81.964463
FR       429.695982
GB         7.017525
GE        13.767386
GR        50.446225
HR        18.291120
HU        43.367564
IE        33.267531
IT       279.107049
LT        12.141747
LU         4.895564
LV         6.979884
MD         5.665620
ME         3.013536
MK         5.009198
NL       115.043796
NO       136.832741
PL       163.569432
PT        51.400833
RO        54.302987
RS        34.299619
SE       131.852598
SI        12.410260
SK        25.627812
XK         6.489130

In [16]:
df_load_hourly.to_csv(dir_out+'load_'+year+'_hourly_entsoe.csv', encoding="utf-8")