# Data preparation of hydro reservoir level filling and inflows derived from aggregation from ENTSO-E transparency

source: https://transparency.entsoe.eu/

Creates the following parsed datasets

- Hourly storage levels per country for selected year for setting storage start and end conditions (reservoir_level_'+year+'_hourly_entsoe_TP.csv) 
- Weekly storage levels per country for selected year for setting storage start and end conditions (reservoir_level_'+year+'_weekly_entsoe_TP.csv) 

Settings in next window

In [91]:
#download files again (yes/no)?
download = "yes"

#set year for data creation
year = '2024'

In [92]:
import pysftp
import sys
import os
import pandas as pd
import numpy as np

In [93]:
os.getcwd() # Leon, checken wo diese Datei bei mir gespeichert ist

'C:\\Users\\UDuer\\Downloads'

In [94]:
#ENTSO-E sftp settings
host = "sftp-transparency.entsoe.eu"
password = "3?mJ}V4us?!L}5E"                
username = "jsavelsberg@ethz.ch"                
port = '22'

In [95]:
dir_out = "../parsed_data/"

In [96]:
fn_additional = "../additional_data.xlsx"

#fn_additional = "additional_data.xlsx" # Leon, meine Ordnerstruktur (muss wieder geändert werden !!!!)
df_countries= pd.read_excel(fn_additional, sheet_name='Countries_EU', index_col="Country")
countries = list(df_countries.index)

In [97]:
#Connect to ENTSO-E Transparency FTP
#for this to work, pysftp 0.2.8 is needed!
path = '/TP_export/'
path_local = os.path.join(os.pardir,'source_data/')

In [98]:
with pysftp.Connection(host=host, username=username, password=password) as sftp:
    print("Connection succesfully established.")

    # show list of files
    files = sftp.listdir('/TP_export/')   
    print(files)

Connection succesfully established.
['AcceptedAggregatedOffers_17.1.D', 'ActivatedBalancingEnergy_17.1.E', 'ActualCapacitiesAndOutlookOnFrequencyRestorationReserveAndReplacementReserve_SOGL_188.3_188.4_189.2_189.3_r3', 'ActualGenerationOutputPerGenerationUnit_16.1.A_r2.1', 'ActualTotalLoad_6.1.A', 'AggregatedBalancingEnergyBids_12.3.E_r3', 'AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D', 'AggregatedGenerationPerType_16.1.B_C', 'AmountAndPricesPaidOfBalancingReservesUnderContract_17.1.B_C_r2', 'AmountOfBalancingReservesUnderContract_17.1.B', 'BalancingBorderCapacityLimitations_IFs_4.3_4.4_r2', 'ChangesInActualAvailabilityOfConsumptionUnits_7.1.B', 'ChangesInActualAvailabilityOfOffshoreGridInfrastructureReasons_10.1.C', 'ChangesInActualAvailabilityOfOffshoreGridInfrastructure_10.1.C', 'ChangesToBidAvailability_IFs_mFRR9.9_aFRR9.6_9.8_r3', 'CommercialSchedulesNetPositions_12.1.F_r3', 'CommercialSchedules_12.1.F_r3', 'CostsOfCongestionManagement_13.1.C', 'Countertrading_13.1.B_r2.1', 'CrossBorderBalancingEnergyActivated_17.1.J', 'CrossBorderBalancingPrices_17.1.J', 'CrossBorderBalancingVolumesOfExchangedBidsAndOffers_17.1.J', 'CrossBorderCapacityForDcLinksIntraday_11.3', 'CrossBorderMarginalPriceForAutomaticFrequencyRestorationReserveStandardProduct_IF_aFRR3.16_r3', 'CrossZonalBalancingCapacity_12.3.H_12.3.I_r3', 'CurrentBalancingState_12.3.A_r3', 'CurrentGenerationForecastForWindAndSolar_14.1.D', 'DayAheadAggregatedGeneration_14.1.C', 'DayAheadFlowBasedAllocations_11.1', 'DayAheadGenerationForecastForWindAndSolar_14.1.D', 'DayAheadTotalLoadForecast_6.1.B', 'ElasticDemands_IFs_mFRR3.4_aFRR3.4_r3', 'EnergyPrices_12.1.D_r3', 'ExchangedReserveCapacity_SOGL_190.3_r3', 'ExpansionAndDismantlingProjects_9.1', 'ExplicitAllocationsAuctionRevenueDaily_12.3.A', 'ExplicitAllocationsAuctionRevenueIntraday_12.3.A', 'ExplicitAllocationsAuctionRevenueMonthly_12.3.A', 'ExplicitAllocationsAuctionRevenueOther_12.3.A', 'ExplicitAllocationsAuctionRevenueWeekly_12.3.A', 'ExplicitAllocationsAuctionRevenueYearly_12.3.A', 'ExplicitAllocationsUseOfTransferCapacityDaily_12.1.A', 'ExplicitAllocationsUseOfTransferCapacityIntraday_12.1.A', 'ExplicitAllocationsUseOfTransferCapacityMonthly_12.1.A', 'ExplicitAllocationsUseOfTransferCapacityOther_12.1.A', 'ExplicitAllocationsUseOfTransferCapacityWeekly_12.1.A', 'ExplicitAllocationsUseOfTransferCapacityYearly_12.1.A', 'Export_log.csv', 'Export_log_r3.csv', 'Export_oce_log_r3.csv', 'Fallbacks_IF_IN7.2_mFRR3.11_aFRR3.10_r3', 'FcrTotalCapacity_187.2', 'FinancialExpensesAndIncomeForBalancing_17.1.I', 'FinancialExpensesAndIncomeForBalancing_17.1.I_r3', 'FlowBasedAllocationsCongestionIncomeDaily_12.1.E', 'FlowBasedAllocationsCongestionIncome_12.1.E_r3', 'ForecastedDayAheadTransferCapacities_11.1', 'ForecastedMonthAheadTransferCapacities_11.1', 'ForecastedWeekAheadTransferCapacities_11.1', 'ForecastedYearAheadTransferCapacities_11.1', 'FrequencyContainmentReserveAmountAndShares_SOGL_187.2_r3', 'FrrActualCapacity_188.4', 'ImbalancePrices_17.1.G_r2.1', 'ImplicitAllocationsCongestionIncome_12.1.E_r3', 'ImplicitAllocationsNetPositions_12.1.E_r3', 'InstalledCapacityProductionUnit_14.1.B', 'InstalledGenerationCapacityAggregated_14.1.A', 'IntradayGenerationForecastForWindAndSolar_14.1.D', 'MonthAheadTotalLoadForecast_6.1.D', 'NettedAndExchangedVolumesPerBorder_IFs_IN3.10_mFRR3.17_r3', 'NettedAndExchangedVolumes_IFs_IN3.10_mFRR3.17_r3', 'OfferedDayAheadTransferCapacityImplicit_11.1', 'OfferedDayAheadTransferCapacity_11.1', 'OfferedIntradayTransferCapacityImplicit_11.1', 'OfferedIntradayTransferCapacity_11.1', 'OfferedMonthAheadTransferCapacity_11.1', 'OfferedOtherTransferCapacity_11.1', 'OfferedTransferCapacitiesContinuous_11.1_r3', 'OfferedTransferCapacitiesExplicit_11.1_r3', 'OfferedTransferCapacitiesImplicit_11.1_r3', 'OfferedWeekAheadTransferCapacity_11.1', 'OfferedYearAheadTransferCapacity_11.1', 'OtherMarketInformation_r3', 'PermanentAllocationLimitations_IFs_4.5_r3', 'PhysicalFlows_12.1.G', 'PlannedUnavailabilityOfConsumptionUnits_7.1.A', 'PricesOfActivatedBalancingEnergy_17.1.F_r3', 'PricesOfProcuredBalancingReserves_17.1.C', 'ProcuredBalancingCapacity_12.3.F', 'ProcuredBalancingCapacity_12.3.F_r3', 'ProductionAndGenerationUnits_r2', 'RedispatchingCrossBorder_13.1.A_r2.1', 'RedispatchingInternal_13.1.A_r2.1', 'Redispatching_13.1.A', 'ResultsOfTheCriteriaApplicationProcess_SOGL_185.4_r3', 'RrActualCapacity_189.3', 'SharesOfFcrCapacity_187.2', 'TotalCapacityAlreadyAllocated_12.1.C_r3', 'TotalCapacityNominated_12.1.B', 'TotalImbalanceVolumes_17.1.H', 'TransferCapacitiesAllocatedWithThirdCountriesDailyImplicit_12.1.H', 'TransferCapacitiesAllocatedWithThirdCountriesDaily_12.1.H', 'TransferCapacitiesAllocatedWithThirdCountriesIntraday_12.1.H', 'TransferCapacitiesAllocatedWithThirdCountriesMonthly_12.1.H', 'TransferCapacitiesAllocatedWithThirdCountriesYearly_12.1.H', 'TransferCapacitiesAllocatedWithThirdCountries_12.1.H_r3', 'UnavailabilityInTransmissionGridReasons_10.1.A_B', 'UnavailabilityInTransmissionGrid_10.1.A_B', 'UnavailabilityOfGenerationUnitsReasons_15.1.A_B', 'UnavailabilityOfGenerationUnits_15.1.A_B', 'UnavailabilityOfProductionUnitsReasons_15.1.C_D', 'UnavailabilityOfProductionUnits_15.1.C_D', 'UseOfAllocatedCrossZonalBalancingCapacity_12.3.H_12.3.I_r2', 'WeekAheadTotalLoadForecast_6.1.C', 'YearAheadForecastMargin_8.1', 'YearAheadTotalLoadForecast_6.1.E', 'zip']

## load data

In [99]:
#set paths and get file names
path_level = path+'AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D/' # Leon, neue Kategorie
path_level_local = path_local+'hydro_ENTSOE/reservoir_level_transparency/'

os.makedirs(path_level_local, exist_ok=True) # Leon, Ordner sicherstellen 

with pysftp.Connection(host=host, username=username, password=password) as sftp:
    print("Connection succesfully established.")
    # show list of files
    files = sftp.listdir(path_level)
    print(files)
    #download files
    if year != "":
        files = [i for i in files if year in i]

Connection succesfully established.
['2014_12_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2015_01_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2015_02_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2015_03_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2015_04_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2015_05_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2015_06_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2015_07_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2015_08_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2015_09_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2015_10_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2015_11_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2015_12_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2016_01_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2016_02_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2016_03_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2016_04_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2016_05_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2016_06_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2016_07_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2016_08_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2016_09_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2016_10_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2016_11_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2016_12_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2017_01_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2017_02_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2017_03_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2017_04_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2017_05_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2017_06_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2017_07_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2017_08_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2017_09_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2017_10_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2017_11_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2017_12_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2018_01_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2018_02_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2018_03_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2018_04_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2018_05_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2018_06_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2018_07_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2018_08_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2018_09_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2018_10_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2018_11_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2018_12_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2019_01_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2019_02_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2019_03_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2019_04_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2019_05_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2019_06_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2019_07_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2019_08_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2019_09_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2019_10_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2019_11_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2019_12_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2020_01_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2020_02_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2020_03_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2020_04_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2020_05_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2020_06_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2020_07_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2020_08_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2020_09_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2020_10_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2020_11_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2020_12_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2021_01_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2021_02_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2021_03_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2021_04_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2021_05_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2021_06_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2021_07_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2021_08_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2021_09_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2021_10_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2021_11_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2021_12_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2022_01_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2022_02_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2022_03_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2022_04_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2022_05_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2022_06_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2022_07_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2022_08_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2022_09_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2022_10_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2022_11_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2022_12_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2023_01_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2023_02_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2023_03_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2023_04_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2023_05_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2023_06_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2023_07_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2023_08_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2023_09_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2023_10_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2023_11_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2023_12_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2024_01_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2024_02_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2024_03_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2024_04_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2024_05_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2024_06_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2024_07_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2024_08_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2024_09_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2024_10_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2024_11_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2024_12_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2025_01_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2025_02_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2025_03_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2025_04_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2025_05_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2025_06_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv', '2025_07_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv']

In [100]:
#download aggregated load data (ActualTotalLoad)
if download =="yes":
    with pysftp.Connection(host=host, username=username, password=password) as sftp:
        for file in files:
            sftp.get(path_level+file,path_level_local+file)
            print('Successfully downloaded file '+file)

Successfully downloaded file 2024_01_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv
Successfully downloaded file 2024_02_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv
Successfully downloaded file 2024_03_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv
Successfully downloaded file 2024_04_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv
Successfully downloaded file 2024_05_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv
Successfully downloaded file 2024_06_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv
Successfully downloaded file 2024_07_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv
Successfully downloaded file 2024_08_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv
Successfully downloaded file 2024_09_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv
Successfully downloaded file 2024_10_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv
Successfully downloaded file 2024_11_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv
Successfully downloaded file 2024_12_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv

In [101]:
#Leon
import chardet
# Eine der Datein testen
test_file = path_level_local + files[0]
print("Prüfe Datei:", test_file)

# Encoding automatisch erkennen
with open(test_file, 'rb') as f:
    result = chardet.detect(f.read(50000)) # nur ersten Teil lesen
print("Erkanntes Encoding:", result)

# Datei mit erkanntem Encoding laden
df_test = pd.read_csv(test_file, sep="\t", encoding=result['encoding'], nrows=5)
print("Spalten:", df_test.columns.tolist())

Prüfe Datei: ..\source_data/hydro_ENTSOE/reservoir_level_transparency/2024_01_AggregatedFillingRateOfWaterReservoirsAndHydroStoragePlants_16.1.D.csv
Erkanntes Encoding: {'encoding': 'UTF-8-SIG', 'confidence': 1.0, 'language': ''}
Spalten: ['DateTime', 'ResolutionCode', 'AreaCode', 'AreaTypeCode', 'AreaName', 'MapCode', 'StoredEnergy', 'DeletedFlag', 'UpdateTime']

In [102]:
#combine files to one data frame
df_level = pd.DataFrame()
for file in files:
    df_temp = pd.read_csv(path_level_local+file,
                          decimal=".",encoding="UTF-8-SIG",sep="\t",
                          parse_dates=True, index_col="DateTime").drop("AreaCode", axis=1)
    #df_level = df_level.append(df_temp)
    df_level = pd.concat([df_level, df_temp], ignore_index=False) # Leon, in pandas 2.0 gibt es .append() nicht mehr als Methode
df_level = df_level[df_level.AreaTypeCode == "CTY"].drop(["AreaTypeCode",'ResolutionCode','AreaName','UpdateTime','DeletedFlag'], axis=1).reset_index()
df_level = df_level.sort_values(by=['DateTime'])
df_level = df_level.rename(columns={"MapCode": "country", 'DateTime':'date','StoredEnergy':'MWh'})
#add timestamp for first hour for all countries for upsampling in next step
for country in countries:
    #df_level = df_level.append(pd.DataFrame([[pd.Timestamp(str(np.int64(year)-1)+'-12-31'),country,float("NaN")]], columns=['date','country','MWh']), ignore_index=True)
    
    # Leon, in pandas 2.0 gibt es .append() nicht mehr als Methode:
    new_row = pd.DataFrame(
    [[pd.Timestamp(str(int(year) - 1) + '-12-31'), country, float("NaN")]],
    columns=['date', 'country', 'MWh']
    )
    df_level = pd.concat([df_level, new_row], ignore_index=True)

df_level.head()

        date country        MWh
0 2024-01-01      GE      440.0
1 2024-01-01      RS   584000.0
2 2024-01-01      ES  9429185.0
3 2024-01-01      FI  3410560.0
4 2024-01-01      FR  2736874.0

In [104]:
#values are reported weekly so we have to resample to hourly values
#upsample with backwardsfill and select baseyear again
df_level_hourly = df_level.pivot(index='date',columns='country')[['MWh']].resample('h').fillna("bfill")
df_level_hourly = df_level_hourly[pd.DatetimeIndex(df_level_hourly.reset_index().date).year.astype(str) == year].stack()
df_level_hourly.tail()

C:\Users\UDuer\AppData\Local\Temp\ipykernel_37480\3952884484.py:3: FutureWarning: DatetimeIndexResampler.fillna is deprecated and will be removed in a future version. Use obj.ffill(), obj.bfill(), or obj.nearest() instead.
  df_level_hourly = df_level.pivot(index='date',columns='country')[['MWh']].resample('h').fillna("bfill")
C:\Users\UDuer\AppData\Local\Temp\ipykernel_37480\3952884484.py:4: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_level_hourly = df_level_hourly[pd.DatetimeIndex(df_level_hourly.reset_index().date).year.astype(str) == year].stack()

                           MWh
date       country
2024-12-30 PT        1872486.0
           RO        1764600.0
           RS         460000.0
           SE       26123000.0
           SI           2600.0

In [105]:
#we also export weekly values
df_level = df_level.set_index(['date','country'])

In [ ]:
df_level.to_csv(dir_out+'reservoir_level_'+year+'_weekly_entsoe_TP.csv', encoding="utf-8", index=True)
df_level_hourly.to_csv(dir_out+'reservoir_level_'+year+'_hourly_entsoe_TP.csv', encoding="utf-8", index=True)