In [1]:
import os
import pandas as pd
import datetime as dt

In [2]:
dir_out = "../parsed_data/"
fn_gen_in = "generation_2017_hourly_entsoe.csv"
fn_cap_in = "capacities.csv"

In [3]:
df_gen_hourly = pd.read_csv(dir_out + fn_gen_in)
df_gen_hourly_max = df_gen_hourly.groupby(['country','tech']).max().drop(columns={'date'})
df_gen_hourly_max.head()

                   output  demand  net_generation
country tech
AT      Biomass    328.00     0.0          328.00
        Gas       4214.20     0.0         4214.20
        HardCoal   537.10     0.0          537.10
        Oil          0.00     0.0            0.00
        Other      122.07     0.0          122.07

In [4]:
df_cap = pd.read_csv(dir_out + fn_cap_in)
df_cap = df_cap[df_cap.year==2017].drop(columns={'year'}).rename(columns={'technology':'tech'}).set_index(['country','tech'])
df_cap.head()

                    capacity
country tech
AL      Oil             97.0
        Reservoir     1534.0
        RunOfRiver     301.0
AT      Biomass        572.0
        Gas           4841.0

In [5]:
df_compare = df_gen_hourly_max.join(df_cap)

In [6]:
df_compare['share'] = df_compare['output']/df_compare['capacity']
df_compare['scale'] = df_compare['capacity']/df_compare['output']

In [7]:
df_compare[df_compare.share > 1]

                         output    demand  net_generation  capacity  \
country tech
BE      Oil            168.8400     0.000        168.8400    158.00
        Other         1106.4900     0.000       1106.4900    391.00
BG      Nuclear       2112.0000     0.000       2112.0000   2000.00
        WindOnshore    803.0000     0.000        803.0000    701.35
CH      Pump          3439.3500     0.000       3439.3500   3089.45
CZ      Other          779.9900     0.000        779.9900    480.00
DE      Nuclear      10334.3325    60.005      10334.3325   9516.00
        Other        19965.4200  1645.605      19965.4200   3680.69
DK      WindOnshore   6704.4100     0.000       6704.4100   4233.34
FI      Nuclear       2795.3000     0.000       2795.3000   2782.00
        Other         1597.7300     0.000       1597.7300   1496.70
FR      Oil           4278.0000     0.000       4278.0000   4098.21
GB      Other         2173.0000     0.000       2173.0000      1.00
        RunOfRiver    1402.5000     0.000       1402.5000    992.00
GR      Gas           5150.0000     0.000       5150.0000   4268.51
HU      Nuclear       1938.9775     0.000       1938.9775   1887.00
        Oil            432.7525     0.790        432.7525    410.00
        Other          173.1675     0.000        173.1675     28.00
IE      Pump           302.5900   301.675        302.5900    292.00
IT      Other        20461.0000     1.000      20461.0000   6923.00
LV      Other          118.0000     0.000        118.0000    109.00
MK      Lignite        830.5200     0.000        830.5200    718.00
        RunOfRiver     399.7000     0.000        399.7000    109.00
        WindOnshore     36.0700     0.000         36.0700     36.00
NL      Nuclear        550.6200     0.000        550.6200    486.00
        WindOnshore   3694.5000     3.870       3694.5000   3675.00
NO      Other          328.9900     0.000        328.9900    125.00
        WindOnshore   1684.8700     0.000       1684.8700   1083.20
PT      HardCoal      1762.7000    61.000       1762.7000   1756.00
        Other           52.3000     0.000         52.3000     17.80
RO      Gas           2441.0000     0.000       2441.0000   1829.00
        HardCoal      2020.2300     0.000       2020.2300   1155.00
        Nuclear       1433.0000     0.000       1433.0000   1300.00
RS      Lignite       6057.0000     0.000       6057.0000   5289.00
SE      Nuclear       9147.0000     0.000       9147.0000   8586.00
        Other         2048.0000     0.000       2048.0000    565.00
SI      Nuclear        699.9000     0.000        699.9000    696.00
        Solar          717.8200     0.000        717.8200    270.54
        WindOnshore      4.5700     0.000          4.5700      3.30
SK      Other          520.5000     0.000        520.5000    443.00

                           share     scale
country tech
BE      Oil             1.068608  0.935797
        Other           2.829898  0.353370
BG      Nuclear         1.056000  0.946970
        WindOnshore     1.144935  0.873412
CH      Pump            1.113256  0.898266
CZ      Other           1.624979  0.615393
DE      Nuclear         1.085995  0.920814
        Other           5.424369  0.184353
DK      WindOnshore     1.583716  0.631426
FI      Nuclear         1.004781  0.995242
        Other           1.067502  0.936767
FR      Oil             1.043870  0.957973
GB      Other        2173.000000  0.000460
        RunOfRiver      1.413810  0.707308
GR      Gas             1.206510  0.828837
HU      Nuclear         1.027545  0.973193
        Oil             1.055494  0.947424
        Other           6.184554  0.161693
IE      Pump            1.036267  0.965002
IT      Other           2.955511  0.338351
LV      Other           1.082569  0.923729
MK      Lignite         1.156713  0.864519
        RunOfRiver      3.666972  0.272705
        WindOnshore     1.001944  0.998059
NL      Nuclear         1.132963  0.882641
        WindOnshore     1.005306  0.994722
NO      Other           2.631920  0.379951
        WindOnshore     1.555456  0.642898
PT      HardCoal        1.003815  0.996199
        Other           2.938202  0.340344
RO      Gas             1.334609  0.749283
        HardCoal        1.749117  0.571717
        Nuclear         1.102308  0.907188
RS      Lignite         1.145207  0.873205
SE      Nuclear         1.065339  0.938668
        Other           3.624779  0.275879
SI      Nuclear         1.005603  0.994428
        Solar           2.653286  0.376891
        WindOnshore     1.384848  0.722101
SK      Other           1.174944  0.851105