In [1]:
import pandas as pd
import numpy as np

In [2]:
fn_in = "../source_data/conventionals/emissions_generation_agg.xlsx"
dir_out = "../parsed_data/"

In [3]:
df = pd.read_excel(fn_in)
df = df.sort_values(by=['country','Technology_entsoe','emi_coef'])
df['id_agg'] = df['country'] + "_" + df['Technology_entsoe']
df = df.drop(df[df["Capacity_entsoe"]=="NaN"].index)
df = df.drop(df[df["emi_coef"]=="NaN"].index)
df.head()

,ets_id,eic_g,eic_p,id,country,eprtr_facilityID,Technology_entsoe,Capacity_entsoe,verified,gen,emi_coef,id_agg
5,AT_43,14W-BLOCK07-L--J,14W-VOEST-KW---0,15,AT,5806.0,gas,153.0,997337,4652123.83,0.214383,AT_gas
3,AT_149,14WENERGIEAGWT4S,14WENERGIE--WT02,12,AT,5779.0,gas,400.0,1425803,3744112.13,0.380812,AT_gas
8,AT_85,14W-GEN-DO3----F,14W-PROD-DO----O,17,AT,5906.0,gas,395.0,2655198,6514773.00,0.407566,AT_gas
4,AT_219,14W-GEN-SIM1---Z,14W-PROD-SIM---P,19,AT,5905.0,gas,828.0,4777752,10697081.75,0.446641,AT_gas
0,AT_134,"14W-KW-THE-KO--3, 14W-KW-THE-M2--7, 14W-KW-THE...",14W-KW-THE-EVN-7,"3, 4, 3, 4, 6, 5, 4, 6, 5",AT,5749.0,gas,722.0,1544879,3034313.68,0.509136,AT_gas

In [6]:
df.describe()

       Capacity_entsoe      verified           gen    emi_coef
count       448.000000  4.480000e+02  4.480000e+02  437.000000
mean        673.488259  7.833269e+06  1.144677e+07         inf
std         625.510458  1.623508e+07  1.799684e+07         NaN
min          12.000000  0.000000e+00  0.000000e+00    0.000000
25%         267.550000  9.054440e+05  1.683693e+06    0.380206
50%         450.000000  3.486834e+06  6.516464e+06    0.596441
75%         835.575000  7.657150e+06  1.269952e+07    1.040221
max        5380.000000  1.807294e+08  1.564600e+08         inf

In [7]:
blocks = df['id_agg'].unique()

In [12]:
df_pivot = df.pivot_table(index=['emi_coef'],columns=['country','Technology_entsoe'],values='Capacity_entsoe', fill_value=0).reset_index()
df_pivot = df_pivot.rolling(2).sum()
df_pivot.tail()

country              emi_coef     AT                             BE       \
Technology_entsoe                gas gas, hardcoal hardcoal biomass  gas
420                 15.496535    0.0           0.0      0.0     0.0  0.0
421                 40.490363    0.0           0.0      0.0     0.0  0.0
422                 81.325452    0.0           0.0      0.0     0.0  0.0
423                204.881874    0.0           0.0      0.0     0.0  0.0
424                       NaN  140.0           0.0      0.0     0.0  0.0

country                         BG   CZ           ...      RO      SE       \
Technology_entsoe hardcoal lignite  gas hardcoal  ... lignite biomass  gas
420                    0.0     0.0  0.0      0.0  ...     0.0     0.0  0.0
421                    0.0     0.0  0.0      0.0  ...     0.0     0.0  0.0
422                    0.0     0.0  0.0      0.0  ...     0.0     0.0  0.0
423                    0.0     0.0  0.0      0.0  ...     0.0     0.0  0.0
424                    0.0     0.0  0.0      0.0  ...     0.0     0.0  0.0

country                         \
Technology_entsoe other fossil
420                        0.0
421                      172.0
422                      172.0
423                        0.0
424                        0.0

country                                                                    \
Technology_entsoe other fossil, hardcoal, other fossil, hardcoal, biomass
420                                                              0.0
421                                                              0.0
422                                                              0.0
423                                                              0.0
424                                                              0.0

country             SI             SK
Technology_entsoe  gas lignite    gas hardcoal lignite
420                0.0     0.0    0.0      0.0     0.0
421                0.0     0.0    0.0      0.0     0.0
422                0.0     0.0    0.0      0.0     0.0
423                0.0     0.0  158.0      0.0     0.0
424                0.0   125.0  158.0      0.0     0.0

[5 rows x 80 columns]

In [10]:
df_sum = df.groupby(['country','Technology_entsoe']).sum()

In [11]:
df_sum.head()

                           Capacity_entsoe  verified          gen  emi_coef
country Technology_entsoe
AT      gas                        3198.96  14279225  33282063.47       inf
        gas, hardcoal              1038.00   3900410   7917195.76  0.492650
        hardcoal                    865.00   4067017   4749182.37  2.642341
BE      biomass                     268.00    988954   7239330.05  0.136608
        gas                        4146.40  49615774  79911736.68  5.889815

In [ ]:
df_ = pd.read_excel(fn_in, skiprows=9, header=[0,1], na_values=["Not Expected", "Not Available"])